<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://static.vecteezy.com/system/resources/previews/005/911/705/non_2x/home-insurance-icon-house-protection-symbol-for-your-web-site-logo-app-ui-design-free-vector.jpg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      Segur Home
    </a>
  </div>
</nav>